### ISSUE TITLE
DB updates - clean up model

### ISSUE THREAD

**Issue by R4tmax** [Teg3z/Wheel-of-Luck#29]
Opening issue regarding my discussion with @Teg3z couple of days back. 

Current data format has changed due to the improvements in the underlying logic, as such all Collections named "Logs$PlayerCombination" are marked for deletion and will be dropped by the end of month (at the latest). 

During my inspections, I noticed that there is a slight missmatch in the "Players" collection, where one of the entires has different fields compared to the others. I would suggest to double check this when possible

EDIT: please see attached screenshot

**Comment by R4tmax** [comment]
![obrazek](https://github.com/user-attachments/assets/0fbeba19-8bb2-4da7-bd57-8abfe195d9e9)

**Comment by Teg3z** [comment]
> During my inspections, I noticed that there is a slight missmatch in the "Players" collection, where one of the entires has different fields compared to the others. I would suggest to double check this when possible

Good catch, i fixed it in the DB, it was an outdated document before I figured out that name property in the DC library is actually users discord ID, so I changed the documents accordingly, but forgot about this one.
