### ISSUE TITLE
GH-action perceives CX_freeze commands as invalid

### ISSUE THREAD

**Issue by R4tmax** [Teg3z/Wheel-of-Luck#31]
As I suspected, automated builds fail. 
What I did NOT foresee, is that they fail pretty much instantly on not recognizing the proper command, I double checked with documentation and everything seems okay there, so I have to somehow manually test this on local.

**Comment by R4tmax** [comment]
Root cause analysis: program was incorrectly failing on missing variables.env files. Currently in a state where WF can successfuly build Linux appimage, tracked branch  is https://github.com/Teg3z/Wheel-of-Luck/tree/BUGFIX/improve-cx-freeze-implementation . 
RPM packages are running into some weird issue I do not fully understand. 

I will need to introduce a Matrix Strategy for handling different OS to maximize effectivity of the build steps. Some people on stackoverflow pointed this out as @Teg3z presented same theory yesterday, I did not find any mentions of this in the freeze docs but we are beyond that now. 
I do not have a time target for this, I will work incrementaly. 

I will also introduce .zip archive from the initial build step for configurations outside of freeze binary packages scope, this might prove a viable alternative for Ubuntu and other APT based machines.

**Comment by Teg3z** [comment]
Issue seems almost done thx to @R4tmax's latest PR #42.

We will see after its tested in a new release and then this issue can be closed

**Comment by Teg3z** [comment]
Well this issue is fixed in #48 as I can see in GH Actions, but it still doesnt attach the installers to the Release, will create new issue.
